databases:
  - name: handson_django_db
    databaseName: handson_django
    user: handson_django
    plan: free

services:
  - type: web
    name: handson_django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn handson_django.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: handson_django_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.2
      - key: WEB_CONCURRENCY
        value: 4